## Optuna

Hyperparameter tuning framework 
We can do hpt on very big datasets 

## Why?
We use gridsearch CV and randomsearch CV normally so why use optuna 
We decide on a search space where we decide on the params to check
for ex 
in random forest we can use n_estimators(50,250,50) and max_depth(1,5,1)
In grid search CV - it does training on all possible params (Dumb af)
Problem - it is very costly , imagine multiple datasets your pc gonna die lol

To solve this problem  we use RandomSearch(Dumb af)
It does on random combinations ie a set amount of combinations 
Saves computations but kinda tukka

To solve this we use Optuna
it uses a different kind of Search which is Bayesian Search (inspired from probability)
    - max_depth and n_estimator -> accurarcy , then we can say that there is a mathematical rln between accurarcy and these features
    - accuracy = f(max_depth,n_estimator)
    - finds the nature of the graph which would give us maxima 
    - this would approximate the graph with different points so on and so forth

### Some key terms
1) Study - The optimisation session is known as study.
2) Trial - A specific set of hp is selected and run that is it
3) Trial Params - The params in the trial are known as Tp's
4) Objective Function - The function we need to find between the acuuracy and the parameters
5) Sampler -  The algo which dictates how you need to find the next point based on previous points.
    TPE - Tree structured parzen estimator (read research paper)

In [1]:
import optuna
from sklearn.datasets import load_diabetes 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

Preprocessing

In [2]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

In [3]:
df = pd.read_csv(url,names = columns)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
cols_with_missing_vals = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
df[cols_with_missing_vals]=df[cols_with_missing_vals].replace(0,np.nan)

In [5]:
df.fillna(df.mean(),inplace=True)

In [6]:
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Data prep

In [7]:
X = df.drop('Outcome' ,axis=1)
y = df['Outcome']

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [9]:
scaler = StandardScaler()

In [10]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
from sklearn.ensemble  import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC

from sklearn.model_selection import cross_val_score

In [12]:
# def the obj function
def Objective(trial):
    # suggest values for hyperparams
    n_estimators = trial.suggest_int('n_estimators',50,200)
    max_depth = trial.suggest_int('max_depth',3,20)

    # create random forest classifier with the hyperparams
    model = RandomForestClassifier(
        n_estimators = n_estimators,
        max_depth=max_depth,
        random_state=42
        )
    # perform 3-fold cross-val and calc accuracy
    score = cross_val_score(model,X_train,y_train,cv = 3 ,scoring = 'accuracy').mean()
    return score

FLOW 
Create objective function (would have the params , model , score / loss / weights etc etc)
put it into study
then optimise the study

In [13]:
study = optuna.create_study(direction='maximize',sampler=optuna.samplers.TPESampler())
study.optimize(Objective,n_trials=75)

[I 2026-03-30 22:26:29,690] A new study created in memory with name: no-name-7d4b4004-93e6-4471-80cf-b78794bc6453
[I 2026-03-30 22:26:30,528] Trial 0 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 196, 'max_depth': 14}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:30,877] Trial 1 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 81, 'max_depth': 19}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:31,945] Trial 2 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 179, 'max_depth': 11}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:32,683] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 98, 'max_depth': 18}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:33,128] Trial 4 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 75, 'max_depth': 4}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:33,622] Trial 5 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 74, 'max_depth': 4}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:34,237] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 108, 'max_depth': 11}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:34,650] Trial 7 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 78, 'max_depth': 19}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:35,488] Trial 8 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 131, 'max_depth': 10}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:35,815] Trial 9 finished with value: 0.756052141527002 and parameters: {'n_estimators': 93, 'max_depth': 3}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:36,482] Trial 10 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 185, 'max_depth': 15}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:37,003] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 148, 'max_depth': 15}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:37,203] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 52, 'max_depth': 16}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:37,766] Trial 13 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 161, 'max_depth': 20}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-03-30 22:26:38,229] Trial 14 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 130, 'max_depth': 13}. Best is trial 14 with value: 0.7765363128491621.
[I 2026-03-30 22:26:38,885] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 199, 'max_depth': 7}. Best is trial 14 with value: 0.7765363128491621.
[I 2026-03-30 22:26:39,417] Trial 16 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 147, 'max_depth': 13}. Best is trial 14 with value: 0.7765363128491621.
[I 2026-03-30 22:26:39,859] Trial 17 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 123, 'max_depth': 8}. Best is trial 14 with value: 0.7765363128491621.
[I 2026-03-30 22:26:40,458] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 172, 'max_depth': 14}. Best is trial 14 with value: 0.7765363128491621.
[I 2026-03-30 22:26:40,893] Trial 19 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 127, 'max_depth': 17}. Best is trial 19 with value: 0.7783985102420857.
[I 2026-03-30 22:26:41,312] Trial 20 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 124, 'max_depth': 17}. Best is trial 19 with value: 0.7783985102420857.
[I 2026-03-30 22:26:41,774] Trial 21 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 125, 'max_depth': 17}. Best is trial 19 with value: 0.7783985102420857.
[I 2026-03-30 22:26:42,178] Trial 22 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 119, 'max_depth': 18}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:42,590] Trial 23 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 115, 'max_depth': 17}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:43,089] Trial 24 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 143, 'max_depth': 20}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:43,486] Trial 25 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 111, 'max_depth': 17}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:43,987] Trial 26 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 139, 'max_depth': 18}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:44,571] Trial 27 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 159, 'max_depth': 16}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:44,931] Trial 28 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 18}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:45,341] Trial 29 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 117, 'max_depth': 13}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:45,667] Trial 30 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 89, 'max_depth': 15}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:46,123] Trial 31 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 125, 'max_depth': 17}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:46,612] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 19}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:46,994] Trial 33 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 105, 'max_depth': 16}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:47,438] Trial 34 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 120, 'max_depth': 20}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:47,988] Trial 35 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 155, 'max_depth': 18}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:48,490] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 132, 'max_depth': 14}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:48,809] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 89, 'max_depth': 17}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:49,064] Trial 38 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 66, 'max_depth': 19}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:49,452] Trial 39 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 108, 'max_depth': 12}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:49,911] Trial 40 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 126, 'max_depth': 10}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:50,355] Trial 41 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 123, 'max_depth': 17}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:50,772] Trial 42 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 113, 'max_depth': 16}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:51,126] Trial 43 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 19}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:51,610] Trial 44 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 18}. Best is trial 22 with value: 0.7802607076350093.
[I 2026-03-30 22:26:52,046] Trial 45 finished with value: 0.7858472998137803 and parameters: {'n_estimators': 121, 'max_depth': 15}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:52,488] Trial 46 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 118, 'max_depth': 14}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:53,009] Trial 47 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 146, 'max_depth': 15}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:53,355] Trial 48 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 95, 'max_depth': 16}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:53,905] Trial 49 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 153, 'max_depth': 15}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:54,396] Trial 50 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 132, 'max_depth': 19}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:54,876] Trial 51 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 126, 'max_depth': 18}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:55,313] Trial 52 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 120, 'max_depth': 17}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:55,716] Trial 53 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 105, 'max_depth': 17}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:56,167] Trial 54 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 128, 'max_depth': 16}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:56,687] Trial 55 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 142, 'max_depth': 15}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:57,167] Trial 56 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 132, 'max_depth': 6}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:57,550] Trial 57 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 111, 'max_depth': 12}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:58,146] Trial 58 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 171, 'max_depth': 16}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:58,618] Trial 59 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 129, 'max_depth': 18}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:59,153] Trial 60 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 13}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:26:59,607] Trial 61 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 122, 'max_depth': 17}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:00,140] Trial 62 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 115, 'max_depth': 17}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:00,588] Trial 63 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 126, 'max_depth': 19}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:01,014] Trial 64 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 107, 'max_depth': 16}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:01,554] Trial 65 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 20}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:01,990] Trial 66 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 120, 'max_depth': 14}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:02,459] Trial 67 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 129, 'max_depth': 18}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:02,994] Trial 68 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 151, 'max_depth': 15}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:03,512] Trial 69 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 135, 'max_depth': 16}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:03,924] Trial 70 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 113, 'max_depth': 17}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:04,361] Trial 71 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 124, 'max_depth': 17}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:04,778] Trial 72 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 17}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:05,230] Trial 73 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 124, 'max_depth': 18}. Best is trial 45 with value: 0.7858472998137803.
[I 2026-03-30 22:27:05,639] Trial 74 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 109, 'max_depth': 18}. Best is trial 45 with value: 0.7858472998137803.

In [14]:
print(study.best_trial.value)
print(study.best_params)

0.7858472998137803
{'n_estimators': 121, 'max_depth': 15}

In [15]:
study = optuna.create_study(direction='maximize',sampler=optuna.samplers.RandomSampler())
study.optimize(Objective,n_trials=75)

[I 2026-03-30 22:27:05,682] A new study created in memory with name: no-name-ec7f8bc0-1efc-4c0d-80ef-5a9301bb06fd
[I 2026-03-30 22:27:05,944] Trial 0 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 79, 'max_depth': 3}. Best is trial 0 with value: 0.7560521415270017.
[I 2026-03-30 22:27:06,225] Trial 1 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 8}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-03-30 22:27:06,792] Trial 2 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 164, 'max_depth': 10}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-03-30 22:27:07,451] Trial 3 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 192, 'max_depth': 16}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-03-30 22:27:08,034] Trial 4 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 168, 'max_depth': 16}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-03-30 22:27:08,329] Trial 5 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 78, 'max_depth': 13}. Best is trial 3 with value: 0.7783985102420856.
[I 2026-03-30 22:27:08,695] Trial 6 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 106, 'max_depth': 12}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:08,988] Trial 7 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 84, 'max_depth': 10}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:09,556] Trial 8 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 167, 'max_depth': 8}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:09,876] Trial 9 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 86, 'max_depth': 8}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:10,201] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 94, 'max_depth': 12}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:10,868] Trial 11 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 200, 'max_depth': 16}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:11,145] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 79, 'max_depth': 19}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:11,744] Trial 13 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 171, 'max_depth': 8}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:12,206] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 101, 'max_depth': 17}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:12,445] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 63, 'max_depth': 6}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:12,906] Trial 16 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 122, 'max_depth': 4}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:13,347] Trial 17 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 122, 'max_depth': 20}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:13,958] Trial 18 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 174, 'max_depth': 9}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:14,445] Trial 19 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 109, 'max_depth': 9}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:15,149] Trial 20 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 197, 'max_depth': 9}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:15,667] Trial 21 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 154, 'max_depth': 17}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:15,972] Trial 22 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 91, 'max_depth': 5}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:16,148] Trial 23 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 55, 'max_depth': 5}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:16,513] Trial 24 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 117, 'max_depth': 4}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:16,722] Trial 25 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 60, 'max_depth': 17}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:17,111] Trial 26 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 108, 'max_depth': 11}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:17,560] Trial 27 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 138, 'max_depth': 10}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:17,757] Trial 28 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 59, 'max_depth': 8}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:18,296] Trial 29 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 169, 'max_depth': 5}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:18,662] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 99, 'max_depth': 18}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:19,203] Trial 31 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 159, 'max_depth': 13}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:19,528] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 104, 'max_depth': 17}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:19,896] Trial 33 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 109, 'max_depth': 18}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:20,403] Trial 34 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 154, 'max_depth': 12}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:20,595] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 58, 'max_depth': 6}. Best is trial 6 with value: 0.7783985102420857.
[I 2026-03-30 22:27:21,051] Trial 36 finished with value: 0.7858472998137803 and parameters: {'n_estimators': 121, 'max_depth': 15}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:21,403] Trial 37 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 111, 'max_depth': 7}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:21,611] Trial 38 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 69, 'max_depth': 3}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:21,861] Trial 39 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 79, 'max_depth': 5}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:22,041] Trial 40 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 53, 'max_depth': 14}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:22,444] Trial 41 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 120, 'max_depth': 11}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:22,856] Trial 42 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 116, 'max_depth': 14}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:23,257] Trial 43 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 118, 'max_depth': 4}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:23,979] Trial 44 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 197, 'max_depth': 16}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:24,495] Trial 45 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 168, 'max_depth': 6}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:24,687] Trial 46 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 57, 'max_depth': 11}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:25,211] Trial 47 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 147, 'max_depth': 20}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:25,824] Trial 48 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 185, 'max_depth': 6}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:26,187] Trial 49 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 108, 'max_depth': 6}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:26,416] Trial 50 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 67, 'max_depth': 11}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:26,986] Trial 51 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 163, 'max_depth': 8}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:27,407] Trial 52 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 114, 'max_depth': 10}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:27,646] Trial 53 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 65, 'max_depth': 7}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:28,288] Trial 54 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 183, 'max_depth': 18}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:28,826] Trial 55 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 159, 'max_depth': 12}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:29,416] Trial 56 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 167, 'max_depth': 19}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:29,767] Trial 57 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 93, 'max_depth': 14}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:30,229] Trial 58 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 132, 'max_depth': 19}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:30,655] Trial 59 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 118, 'max_depth': 13}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:31,083] Trial 60 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 121, 'max_depth': 10}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:31,724] Trial 61 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 188, 'max_depth': 8}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:32,252] Trial 62 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 128, 'max_depth': 9}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:32,757] Trial 63 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 19}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:33,256] Trial 64 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 142, 'max_depth': 9}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:33,605] Trial 65 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 90, 'max_depth': 19}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:33,875] Trial 66 finished with value: 0.756052141527002 and parameters: {'n_estimators': 73, 'max_depth': 10}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:34,563] Trial 67 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 193, 'max_depth': 15}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:35,033] Trial 68 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 131, 'max_depth': 12}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:35,437] Trial 69 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 114, 'max_depth': 18}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:35,818] Trial 70 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 115, 'max_depth': 5}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:36,471] Trial 71 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 164, 'max_depth': 17}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:37,089] Trial 72 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 165, 'max_depth': 8}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:37,534] Trial 73 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 113, 'max_depth': 13}. Best is trial 36 with value: 0.7858472998137803.
[I 2026-03-30 22:27:37,795] Trial 74 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 66, 'max_depth': 4}. Best is trial 36 with value: 0.7858472998137803.

In [16]:
space_search = {
    'n_estimators' : [50,100,150,200],
    'max_depth' : [5,10,15,20]
}
study = optuna.create_study(direction='maximize',sampler=optuna.samplers.GridSampler(space_search))
study.optimize(Objective,n_trials=75)

[I 2026-03-30 22:27:37,821] A new study created in memory with name: no-name-cf285ffc-1837-41e8-a061-f4e6bc8e8891
[I 2026-03-30 22:27:38,229] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-30 22:27:38,777] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-30 22:27:38,983] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-30 22:27:39,307] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-30 22:27:39,666] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-30 22:27:39,839] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-30 22:27:40,272] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-30 22:27:40,834] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-30 22:27:41,437] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-30 22:27:42,157] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-30 22:27:43,481] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-30 22:27:44,826] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-30 22:27:45,730] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-30 22:27:45,901] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-30 22:27:46,245] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-30 22:27:46,431] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

Some Features
1) We have multiple samplers 
    Random Search
    Grid Search
    ....
2) Visualisation we can make OHP (optimisation history plot)
    - Parallel Coodinate plot - rln bw accuracy max deth and estimaors
    - Slice Plot 
    - Contour Plot
    - Importance Plot
3) Define By Run - We can create dynamic search spaces
    - consider i need to train multiple models then we can do it by only doing hpt once
    - we can choose the algos as a hyperparams
    for ex algo = [SVM , XGB , RF , LR]
    then we can have different search spaces for these algos and to choose which search space depends on which algo hyperparameter
    - we can also use distributed computing (kinda use diff comps to train faster)

In [17]:
# def the obj function
def Objective_multi(trial):
    classifier_name = trial.suggest_categorical('classifier',['SVM','RandomForest','GradientBoosting'])

    if classifier_name == 'SVM':
    #SVM hyperparams
        c = trial.suggest_float('C',0.1,100,log = True)
        kernel = trial.suggest_categorical('kernel',['linear','rbf','poly','sigmoid'])
        gamma = trial.suggest_categorical('gamma',['scale','auto'])
        
        model = SVC(C=c,kernel = kernel ,gamma = gamma , random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        ) 

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )
        
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [18]:
study = optuna.create_study(direction='maximize')
study.optimize(Objective_multi, n_trials=100)

[I 2026-03-30 22:27:46,468] A new study created in memory with name: no-name-d2544c41-d2e7-42fc-9fb7-d3bab87a58b9
[I 2026-03-30 22:27:46,894] Trial 0 finished with value: 0.7560521415270017 and parameters: {'classifier': 'RandomForest', 'n_estimators': 132, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 0 with value: 0.7560521415270017.
[I 2026-03-30 22:27:46,946] Trial 1 finished with value: 0.7318435754189944 and parameters: {'classifier': 'SVM', 'C': 37.41211769973061, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 0 with value: 0.7560521415270017.
[I 2026-03-30 22:27:47,346] Trial 2 finished with value: 0.7783985102420857 and parameters: {'classifier': 'RandomForest', 'n_estimators': 146, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-03-30 22:27:47,377] Trial 3 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.822097555291966, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:47,781] Trial 4 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 60, 'learning_rate': 0.06341721036307893, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:47,800] Trial 5 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.22219103356591957, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:48,396] Trial 6 finished with value: 0.7783985102420857 and parameters: {'classifier': 'RandomForest', 'n_estimators': 225, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:48,959] Trial 7 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 170, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:49,401] Trial 8 finished with value: 0.7560521415270017 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 58, 'learning_rate': 0.016370991446589205, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:51,101] Trial 9 finished with value: 0.7448789571694601 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 252, 'learning_rate': 0.18122546125436298, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 7}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:51,140] Trial 10 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 9.44613781049331, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:51,181] Trial 11 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.032176766183012, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:51,200] Trial 12 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.890545752963516, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:51,248] Trial 13 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 20.00427320822654, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:51,279] Trial 14 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 1.230541649750166, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:51,292] Trial 15 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.3895690102622449, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:51,513] Trial 16 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 85.95447553482768, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:51,550] Trial 17 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 10.139674102172405, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:51,566] Trial 18 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 2.0234800957449997, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:52,511] Trial 19 finished with value: 0.7635009310986964 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 300, 'learning_rate': 0.012125079896707499, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:52,525] Trial 20 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.2715446542315375, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:52,569] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.847149739809251, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:52,617] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 13.528378189244833, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:52,639] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 5.093904256391865, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:52,744] Trial 24 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 31.757564169056852, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:52,776] Trial 25 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.9765766247598755, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-03-30 22:27:52,792] Trial 26 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6797509165954956, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 26 with value: 0.7858472998137803.
[I 2026-03-30 22:27:52,810] Trial 27 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 0.47300263124169084, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 26 with value: 0.7858472998137803.
[I 2026-03-30 22:27:53,594] Trial 28 finished with value: 0.7560521415270017 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 113, 'learning_rate': 0.2628531572301587, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 26 with value: 0.7858472998137803.
[I 2026-03-30 22:27:54,259] Trial 29 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 206, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 26 with value: 0.7858472998137803.
[I 2026-03-30 22:27:55,610] Trial 30 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 296, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 26 with value: 0.7858472998137803.
[I 2026-03-30 22:27:55,632] Trial 31 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10688887431895903, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 31 with value: 0.7877094972067038.
[I 2026-03-30 22:27:55,653] Trial 32 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12247555131313376, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:55,668] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10590096009546558, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:55,689] Trial 34 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11237401083085594, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:55,726] Trial 35 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 0.10409237276968046, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:55,749] Trial 36 finished with value: 0.7486033519553073 and parameters: {'classifier': 'SVM', 'C': 0.12833347932088815, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:55,772] Trial 37 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17983006763538728, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:56,080] Trial 38 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 101, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:58,518] Trial 39 finished with value: 0.7243947858472999 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 255, 'learning_rate': 0.04573420062703784, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:58,540] Trial 40 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3391946771950148, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:58,554] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17159952693866465, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:58,572] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10178093864401999, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:58,586] Trial 43 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1710703758785297, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:58,607] Trial 44 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.3863203858089311, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:58,625] Trial 45 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16691399199401336, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:59,228] Trial 46 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 195, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:27:59,246] Trial 47 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6380091684134275, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:01,477] Trial 48 finished with value: 0.7281191806331471 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 252, 'learning_rate': 0.08240157370799302, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 6}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:01,511] Trial 49 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.22072377633905613, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:01,575] Trial 50 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14652099745516192, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:01,612] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14511632253448406, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:01,640] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11762245139959185, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:01,678] Trial 53 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.26225447345210473, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:01,700] Trial 54 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14294640712389456, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:01,727] Trial 55 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1542286303606445, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:01,750] Trial 56 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.27911001360674975, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:01,777] Trial 57 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.21402545400452838, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:01,806] Trial 58 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4691629436116911, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:02,501] Trial 59 finished with value: 0.7746741154562384 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 81, 'learning_rate': 0.02299182246102243, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:02,521] Trial 60 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13600604060233856, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:02,540] Trial 61 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17712239778790176, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:02,557] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14945627331667677, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:02,571] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1350923535500234, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:02,591] Trial 64 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.25128736433357257, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:02,612] Trial 65 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.3487367704164952, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:03,131] Trial 66 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 160, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:03,160] Trial 67 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.13353112174754458, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:03,172] Trial 68 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2378010554365103, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:03,185] Trial 69 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.20004480912748068, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:03,213] Trial 70 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 0.8358419900864391, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:03,229] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13693391320970205, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:03,250] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12937568017094592, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:03,267] Trial 73 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10439319507834342, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:03,284] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14924031067897786, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:03,289] Trial 75 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.20452860441094686, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:03,316] Trial 76 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3138160985119745, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:05,287] Trial 77 finished with value: 0.7337057728119181 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 274, 'learning_rate': 0.029546604070706053, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:05,309] Trial 78 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1008050526543543, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:05,328] Trial 79 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13534739797560763, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:06,022] Trial 80 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 216, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 32 with value: 0.7895716945996275.
[I 2026-03-30 22:28:06,037] Trial 81 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.159330862302535, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 32 with value: 0.7895716945996275.

In [21]:
print(study.best_params)
print(study.best_trial.value)

{'classifier': 'SVM', 'C': 0.12247555131313376, 'kernel': 'linear', 'gamma': 'scale'}
0.7895716945996275

In [23]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.756052,2026-03-30 22:27:46.469017,2026-03-30 22:27:46.894004,0 days 00:00:00.424987,NaN,True,RandomForest,NaN,NaN,NaN,5.0,9.0,7.0,132.0,COMPLETE
1,1,0.731844,2026-03-30 22:27:46.894004,2026-03-30 22:27:46.946094,0 days 00:00:00.052090,37.412118,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.778399,2026-03-30 22:27:46.947166,2026-03-30 22:27:47.346124,0 days 00:00:00.398958,NaN,False,RandomForest,NaN,NaN,NaN,17.0,9.0,4.0,146.0,COMPLETE
3,3,0.785847,2026-03-30 22:27:47.346124,2026-03-30 22:27:47.377848,0 days 00:00:00.031724,8.822098,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,0.750466,2026-03-30 22:27:47.377848,2026-03-30 22:27:47.781162,0 days 00:00:00.403314,NaN,NaN,GradientBoosting,NaN,NaN,0.063417,11.0,9.0,5.0,60.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.785847,2026-03-30 22:28:07.325434,2026-03-30 22:28:07.353121,0 days 00:00:00.027687,1.717711,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.785847,2026-03-30 22:28:07.354120,2026-03-30 22:28:07.368675,0 days 00:00:00.014555,0.225258,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.767225,2026-03-30 22:28:07.368675,2026-03-30 22:28:08.041392,0 days 00:00:00.672717,NaN,True,RandomForest,NaN,NaN,NaN,5.0,2.0,6.0,180.0,COMPLETE
98,98,0.787709,2026-03-30 22:28:08.043392,2026-03-30 22:28:08.119799,0 days 00:00:00.076407,0.173213,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.789572,2026-03-30 22:28:08.119799,2026-03-30 22:28:08.179764,0 days 00:00:00.059965,0.126446,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE